### ISSUE TITLE
Minor comments from all reviews

### ISSUE THREAD

**Issue by Alanocallaghan** [VallejosGroup/BASiCSWorkflow#42]
These are mostly text edits that should be quick and easy to address.

- [x] In the chunk starting ## Moles per microliter, I had to edit the first line of the code chunk to get it to work. Perhaps it has been malformatted?
- [x] \log is a symbol and should always be lower-case (note: I'm not making all the "log2" in plot labels subscripted)
- [x] Figure 12 there is a typo in the legend "\log_{1}0 -> \log_{10}".
- [x] In the abstract, you write "strong technical noise". I don’t quite understand what "strong" is adding here. 
- [x] In the first code chunks, in `website <- " https …” I think there is an initial space which stops this from running correctly.
- [x] Remember to include spaces after commas e.g. [a, ] rather than [a,], it is much clearer to read.
- [x] I think it would be better to load all the packages at the beginning, I had to restart my session several times to install the packages that I realized I needed x% of the way through the workflow.
- [x] newlines in `website` strings resulting in mal-formed URL.
- [x] ^ rendered in some odd font that wouldn't execute when I copied a chunk into Rstudio.
- [x] concentration.in..Mix.1.attomoles.ul was missing an `.`
- [x] It seemed that when I ran the `BASiCS_DetectHVG` function as specified, I got a couple of warning messages: "The posterior probability threshold chosen via EFDR calibration is too low. Probability threshold automatically set equal to 'ProbThresholdM'."
  **Response**: This is a message, not a warning. Could add the EFDR/EFNR plot to the manuscript and explain that it's fine.
- [x] Figure 15: Caption says "log2 change in expression against against log mean expression for genes with higher residual over-dispersion in naive (A) cells and active (D) cells", but seems to refer to panels A and C.
  - [ ] More broadly, it's not really clear what sort of conclusions we are supposed to draw from this sort of figure.
- [x] Introduction, 2nd paragraph: “Moreover, these variability estimates can also be inflated by the technical noise that is typically observed in scRNA-seq data”
  Comment: Please illustrate with examples of technical noise as presented above for extrinsic and intrinsic noise, e.g. RNA differential degradation, ligation bias, etc.

- [ ] Introduction, 3rd paragraph: “However, despite the benefits associated to the use of spike-ins and UMIs, these are not available for all scRNA-seq protocols.”
  Comment: Please provide a reason - something like “due to the very nature of the assay, which isolates library prep from external spike-ins and uses UMIs to map single-cell libraries…” or that spike-ins added to the library after pooling limit the full advantage of using them across single-cell populations.

> Cata: I think our response needs to differentiate between spike-ins and UMIs. We could write something along the lines of what Haque et al (2017) has: *In general, spike-in RNAs are not compatible with droplet-based approaches, whereas UMIs are typically used in protocols where only the 3’-ends of transcripts are sequenced, such as CEL-seq2, Drop-seq and MARS-seq [10, 45, 60]*. Note, however, that technology is evolving (see [this paper](https://www.nature.com/articles/s41592-022-01446-x)). Perhaps we can change the sentence to say "... these are not routinely available ...". I haven't been able to find a reference yet, but I believe that spike-ins in 10X could be expensive, as you would technically need to add spike-ins to all droplets, even though some of cells won't capture a cell. For now, I added a note in the Rmd file: "[**EXPAND to provide reasons why**]"

- [x] Methods, 2nd paragraph: “Mean parameters μi quantify the overall expression for each gene i across the cell population under study.” 
  Comment: Please define cell population as sample (all cells within a scRNA-seq assay) or post-processing UMAP, t-SNE, or similar clustering grouping. I understood the latter, but readers should be certain, and we need to understand which step these parameters refer to.

https://github.com/VallejosGroup/BASiCSWorkflow/blob/23f82e880091cec2765bfc3315e7a824096aae9a/Workflow.Rmd#L281-L287

- [ ] After Figure 5: “These thresholds can vary across datasets and should be informed by gene-specific QC metrics such as those shown in Figure 5 as well as prior knowledge about the cell types and conditions being studied, where available”.
  Comment: I understand this is not the intent of this study, but if possible include some rationale behind thresholds for QCing gene exclusion based on types and conditions. Maybe bringing the choice for the example explored here.

> Cata: I think the statement we had about *prior knowledge* is a bit vague. I was also looking at OSCA and it seems that this step has been removed from their examples (the ones I saw were doing feature selection by identifying HVGs directly). Maybe we need to rephrase a bit? 

- [x] After spike-in calculation step: “To update the sce_naive and sce_active objects, the user must create a data.frame whose first column contains the spike-in labels (e.g. ERCC-00130) and whose second column contains the number of molecules calculated above. We add this as row metadata for altExp (sce_naive) and altExp (sce_active).”
  Comment: By ‘update’, do the authors mean ‘update after normalisation with spike-in’? If so, please specify.

https://github.com/VallejosGroup/BASiCSWorkflow/blob/64f1ce81b3fcd467cda3a44652ae6f5b10fe8e97/Supplements.Rmd#L534

- [x] MCMC diagnostics: I would kindly ask if they can add the reason why this is needed: “to ensure that comparisons of gene expression are not random” or something in that direction. Readers will appreciate it.

https://github.com/VallejosGroup/BASiCSWorkflow/blob/8dec9e9caae5540634fe061f71fd88c51f590125/Workflow.Rmd#L498-L500

**Comment by catavallejos** [comment]
I implemented some extra changes in the Rmd files. Only two items remain unresolved here, see comments above.

**Comment by Alanocallaghan** [comment]
Great, thanks! I'll put these into a response doc later and start working on the rest of the major comments

**Comment by catavallejos** [comment]
I am closing this as most things have been addressed already in the rebuttal. I will start a new issue to track what remains unresolved.
