### ISSUE TITLE
Create a cartoon/diagram to illustrate the BASiCS model(s)

### ISSUE THREAD

**Issue by catavallejos** [VallejosGroup/BASiCSWorkflow#45]
- [ ] edit the model description accordingly when ready
- [ ] highlight the importance of our prior specification (Eling et al results)

**Comment by catavallejos** [comment]
Include a panel to illustrate the mean/OD trend and the residuals

**Comment by Alanocallaghan** [comment]
I'm happy to draw something up but I've not had much of a think about what exactly it should look like/what it needs to convey

**Comment by catavallejos** [comment]
I am kind of leaving this until the end, to make sure that everything is covered. So far, I was thinking to have 1 panel with a DAG that shows the structure of the model, highlighting mu and delta (perhaps with a variation for the no-spikes case) and a second panel for the regression/joint prior.

**Comment by catavallejos** [comment]
also, we may want to incorporate the var decomposition?
